### ISSUE TITLE
Implementation of ATR based box scaling

### ISSUE THREAD

**Issue by Pipsopath** [swaschke/pypnf#3]
Hi there!
Would it be possible to add the method of box scaling by the Average True Range of n days?

**Comment by fivethreeo** [comment]
I would like that aswell. But I think it is a bit hard since the code precalculates all the boxes. Atr must be done on the go. So since this code relies on the indexes of boxes in a list it can be difficult to adapt.

I ported all the code to javascript so i know it intimately by now.

**Comment by fivethreeo** [comment]
It seems I am wrong. ATR should be calculated only at the beginning of the chart. Should be a easy feat to add then. Just calc the boxsize using atr and use a static boxsize as normal.
